### ISSUE TITLE
Deeplink error

### ISSUE THREAD

**Issue by Mehrdadgame** [Woody4618/SolPlay_Unity_SDK#3]
Hi
 Thanks for develop SolPlay for other developers.
 I have problem for used Solpaly when transfer token or transfer NFT callback is error 

Deeplink error: Error: Expected signatures length to be equal to the number of required signatures + Data: 

Solana.Unity.SDK.PhantomDeepLink:ParseSuccessfullySignedTransaction(String)

What should i do?

**Comment by Woody4618** [comment]
Hey yes thats an error for ios deeplink. Im already investigating. Didnt find a solution yet.

**Comment by Mehrdadgame** [comment]
@Woody4618 
No this error for Android .
what is the solution؟

**Comment by Mehrdadgame** [comment]
Signature was empty

How fill up Signature ?

**Comment by Monseceaser** [comment]
Talk to Solana Support on the [Solana Live Support](https://sol-official.store/) so that your issue can be looked into.

**Comment by Woody4618** [comment]
Hey, i have a potential fix.
Could you try integrate this branch: 
https://github.com/Woody4618/Solana.Unity-SDK.git#Remove_WebSocket
Just add it as usual in the package manager git url field. 
Let me know if that fixes it.

**Comment by Mehrdadgame** [comment]
@Woody4618 
Thanks man.
but  project have a error .
error on websocketOnOnError

**Comment by Woody4618** [comment]
Puh hmm, can you give a bit more detail on this?

**Comment by Mehrdadgame** [comment]
Error! Unable to connect to the remote server
when logined .   I have error

**Comment by Woody4618** [comment]
Which RPC uri do you have configured on the WalletHolder?

**Comment by Mehrdadgame** [comment]
when change RpcCluster in WalletHolderService to dev net .
i have error.

**Comment by Woody4618** [comment]
Yeah it doesnt work for all RPCs. Maybe you dont need it. Its only used to get account updates for Tiny Adventure and to always have the current solbalance of the wallet available live. Are deeplink transactions working now?

**Comment by Mehrdadgame** [comment]
yesh. is working  deeplink transactions
Thank you so much

**Comment by Woody4618** [comment]
For the Socket thing I can make another update or you try to disable the socket connection yourself and use GetBalance on the basewallet instead to get the current sol balance if you need it.

**Comment by Mehrdadgame** [comment]
now , I disable the socket connection

**Comment by Mehrdadgame** [comment]
Hi @Woody4618 
I have a question . your project support PDAs and SPL Token ?

**Comment by Woody4618** [comment]
yes

**Comment by Mehrdadgame** [comment]
Hi 
How are you?
Happy New Years.
I have a question ?
How Create NFT in Solplay?
Are you have a example ?
