### ISSUE TITLE
Error in Mint NFT with Metadata V3

### ISSUE THREAD

**Issue by Mehrdadgame** [Woody4618/SolPlay_Unity_SDK#4]
Hi 
I wanna mint NFT with metadata v3 but when created NFT in not load json data.
Can you help me for create NFT ?
![Capture](https://user-images.githubusercontent.com/72225846/211868457-5e011156-9cd5-4339-9975-62365d75986f.PNG)

**Comment by Mehrdadgame** [comment]
`{
	"name":  "HL Bee #1000043",
	"symbol": "HL_GEN",
	 "description": "The Honeyland Genesis collection is limited to 11,000 NFTs, made up of 1,000 Queen Bees and 10,000 Bees. These will be minted as eggs and can be hatched into Bees for play in Honeyland by using the hatching machine from any open Honeyland universe.",
	"seller_fee_basis_points": 100,
	"image":  "https://content.honey.land/images/bees/Honeyland%20Generations/Generational_Queen_Egg_Gen1.jpg",
	"animation_url": null,
	 "attributes": [
	    {
            "trait_type": "ID",
            "value": "1000043"
        }, {
            "trait_type": "Type",
            "value": "Queen"
        }, {
            "trait_type": "Generation",
            "value": "First Generation"
        }, {
            "trait_type": "Universe",
            "value": "Earth"
        }, {
            "trait_type": "Like",
            "value": "90\u2019s cartoons"
        }, {
            "trait_type": "Dislike",
            "value": "Milk"
        }
    ],
	"external_url":"https://honey.land",
	 "properties": {
        "category": "image",
       "creators": [
			{
				"address": "CuLyPDyDRSFoPYnNK9ZZMPDFz2nPq2cY3mrLfdQC6aGz",
				"verified": true,
				"share": 100
			}
		],
        "files": [{
                "type": "image/png",
                "uri": "https://content.honey.land/images/bees/Honeyland%20Generations/Generational_Queen_Egg_Gen1.jpg"
            }
        ]
    }
}`

This is json NFT

**Comment by Mehrdadgame** [comment]
`{
	"name":  "",
	"symbol": "HL",
	 "description": ".",
	"seller_fee_basis_points": 100,
	"image":  "",
	"animation_url": null,
	 "attributes": [
	    {
            "trait_type": "ID",
            "value": "1000043"
        }, {
            "trait_type": "Type",
            "value": ""
        }, {
            "trait_type": "",
            "value": ""
        }, {
            "trait_type": "",
            "value": ""
        }, {
            "trait_type": "",
            "value": ""
        }, {
            "trait_type": "",
            "value": ""
        }
    ],
	"external_url":"https://",
	 "properties": {
        "category": "image",
       "creators": [
			{
				"address": "",
				"verified": true,
				"share": 100
			}
		],
        "files": [{
                "type": "image/png",
                "uri": ""
            }
        ]
    }
}`

this is a my json

**Comment by Mehrdadgame** [comment]
`{
    "animation_url": "",
    "attributes": [{
            "trait_type": "ID",
            "value": "1000011"
        }, {
            "trait_type": "Type",
            "value": ""
        }, {
            "trait_type": "",
            "value": "First "
        }, {
            "trait_type": "",
            "value": ""
        }, {
            "trait_type": "",
            "value": ""
        }, {
            "trait_type": "",
            "value": ""
        }
    ],
    "collection": {
        "family": "",
        "name": ""
    },
    "description": "",
    "external_url": "",
    "image": "",
    "name": "",
    "properties": {
        "category": "",
        "creators": [{
                "address": "",
                "share": 90.0
            }, {
                "address": "",
                "share": 10.0
            }
        ],
        "files": [{
                "type": "image/png",
                "uri": ""
            }
        ]
    },
    "seller_fee_basis_points": 500.0,
    "symbol": "HL"
}
`
this is json file

**Comment by Woody4618** [comment]
Hey, looks like the Image Uri is missing. So it cant load the image.

**Comment by Woody4618** [comment]
Close due to no reply and probably an NFT error since the Nft doesnt have an Uri set.
